#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x62F25B592B6F76DA (github@pureftpd.org)
#
Name     : libsodium
Version  : 1.0.17
Release  : 14
URL      : https://github.com/jedisct1/libsodium/releases/download/1.0.17/libsodium-1.0.17.tar.gz
Source0  : https://github.com/jedisct1/libsodium/releases/download/1.0.17/libsodium-1.0.17.tar.gz
Source99 : https://github.com/jedisct1/libsodium/releases/download/1.0.17/libsodium-1.0.17.tar.gz.sig
Summary  : A modern and easy-to-use crypto library
Group    : Development/Tools
License  : ISC
Requires: libsodium-lib = %{version}-%{release}
Requires: libsodium-license = %{version}-%{release}
BuildRequires : llvm

%description
[![Build Status](https://travis-ci.org/jedisct1/libsodium.svg?branch=master)](https://travis-ci.org/jedisct1/libsodium?branch=master)
[![Windows build status](https://ci.appveyor.com/api/projects/status/fu8s2elx25il98hj?svg=true)](https://ci.appveyor.com/project/jedisct1/libsodium)
[![Coverity Scan Build Status](https://scan.coverity.com/projects/2397/badge.svg)](https://scan.coverity.com/projects/2397)

%package dev
Summary: dev components for the libsodium package.
Group: Development
Requires: libsodium-lib = %{version}-%{release}
Provides: libsodium-devel = %{version}-%{release}

%description dev
dev components for the libsodium package.


%package lib
Summary: lib components for the libsodium package.
Group: Libraries
Requires: libsodium-license = %{version}-%{release}

%description lib
lib components for the libsodium package.


%package license
Summary: license components for the libsodium package.
Group: Default

%description license
license components for the libsodium package.


%prep
%setup -q -n libsodium-1.0.17

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550689410
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1550689410
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libsodium
cp LICENSE %{buildroot}/usr/share/package-licenses/libsodium/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/sodium/core.h
/usr/include/sodium/crypto_aead_aes256gcm.h
/usr/include/sodium/crypto_aead_chacha20poly1305.h
/usr/include/sodium/crypto_aead_xchacha20poly1305.h
/usr/include/sodium/crypto_auth.h
/usr/include/sodium/crypto_auth_hmacsha256.h
/usr/include/sodium/crypto_auth_hmacsha512.h
/usr/include/sodium/crypto_auth_hmacsha512256.h
/usr/include/sodium/crypto_box.h
/usr/include/sodium/crypto_box_curve25519xchacha20poly1305.h
/usr/include/sodium/crypto_box_curve25519xsalsa20poly1305.h
/usr/include/sodium/crypto_core_ed25519.h
/usr/include/sodium/crypto_core_hchacha20.h
/usr/include/sodium/crypto_core_hsalsa20.h
/usr/include/sodium/crypto_core_salsa20.h
/usr/include/sodium/crypto_core_salsa2012.h
/usr/include/sodium/crypto_core_salsa208.h
/usr/include/sodium/crypto_generichash.h
/usr/include/sodium/crypto_generichash_blake2b.h
/usr/include/sodium/crypto_hash.h
/usr/include/sodium/crypto_hash_sha256.h
/usr/include/sodium/crypto_hash_sha512.h
/usr/include/sodium/crypto_kdf.h
/usr/include/sodium/crypto_kdf_blake2b.h
/usr/include/sodium/crypto_kx.h
/usr/include/sodium/crypto_onetimeauth.h
/usr/include/sodium/crypto_onetimeauth_poly1305.h
/usr/include/sodium/crypto_pwhash.h
/usr/include/sodium/crypto_pwhash_argon2i.h
/usr/include/sodium/crypto_pwhash_argon2id.h
/usr/include/sodium/crypto_pwhash_scryptsalsa208sha256.h
/usr/include/sodium/crypto_scalarmult.h
/usr/include/sodium/crypto_scalarmult_curve25519.h
/usr/include/sodium/crypto_scalarmult_ed25519.h
/usr/include/sodium/crypto_secretbox.h
/usr/include/sodium/crypto_secretbox_xchacha20poly1305.h
/usr/include/sodium/crypto_secretbox_xsalsa20poly1305.h
/usr/include/sodium/crypto_secretstream_xchacha20poly1305.h
/usr/include/sodium/crypto_shorthash.h
/usr/include/sodium/crypto_shorthash_siphash24.h
/usr/include/sodium/crypto_sign.h
/usr/include/sodium/crypto_sign_ed25519.h
/usr/include/sodium/crypto_sign_edwards25519sha512batch.h
/usr/include/sodium/crypto_stream.h
/usr/include/sodium/crypto_stream_chacha20.h
/usr/include/sodium/crypto_stream_salsa20.h
/usr/include/sodium/crypto_stream_salsa2012.h
/usr/include/sodium/crypto_stream_salsa208.h
/usr/include/sodium/crypto_stream_xchacha20.h
/usr/include/sodium/crypto_stream_xsalsa20.h
/usr/include/sodium/crypto_verify_16.h
/usr/include/sodium/crypto_verify_32.h
/usr/include/sodium/crypto_verify_64.h
/usr/include/sodium/export.h
/usr/include/sodium/randombytes.h
/usr/include/sodium/randombytes_salsa20_random.h
/usr/include/sodium/randombytes_sysrandom.h
/usr/include/sodium/runtime.h
/usr/include/sodium/utils.h
/usr/include/sodium/version.h
/usr/lib64/libsodium.so
/usr/lib64/pkgconfig/libsodium.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsodium.so.23
/usr/lib64/libsodium.so.23.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libsodium/LICENSE
